from __future__ import annotations


# Small, code-reviewed exceptions whose units are defined by schema comments or
# stable openpilot conventions. The generated audit resource remains broad, but
# these values take precedence and are intentionally easy to review in diffs.
CURATED_FIELD_UNITS = {
  "carState.vEgo": "m/s",
  "carState.vEgoRaw": "m/s",
  "carState.vEgoCluster": "m/s",
  "carState.aEgo": "m/s^2",
  "carState.steeringAngleDeg": "deg",
  "carState.steeringRateDeg": "deg/s",
  "carState.yawRate": "rad/s",
  "radarState.leadOne.dRel": "m",
  "radarState.leadOne.yRel": "m",
  "radarState.leadOne.vRel": "m/s",
  "radarState.leadOne.aRel": "m/s^2",
  "radarState.leadTwo.dRel": "m",
  "radarState.leadTwo.yRel": "m",
  "radarState.leadTwo.vRel": "m/s",
  "radarState.leadTwo.aRel": "m/s^2",
  "gpsLocation.latitude": "deg",
  "gpsLocation.longitude": "deg",
  "gpsLocation.altitude": "m",
  "gpsLocation.speed": "m/s",
  "gpsLocation.bearingDeg": "deg",
  "gpsLocation.horizontalAccuracy": "m",
  "gpsLocation.vNED[]": "m/s",
  "gpsLocation.verticalAccuracy": "m",
  "gpsLocation.bearingAccuracyDeg": "deg",
  "gpsLocationExternal.latitude": "deg",
  "gpsLocationExternal.longitude": "deg",
  "gpsLocationExternal.altitude": "m",
  "gpsLocationExternal.speed": "m/s",
  "gpsLocationExternal.bearingDeg": "deg",
  "gpsLocationExternal.horizontalAccuracy": "m",
  "gpsLocationExternal.vNED[]": "m/s",
  "gpsLocationExternal.verticalAccuracy": "m",
  "gpsLocationExternal.bearingAccuracyDeg": "deg",
  "roadCameraState.timestampSof": "ns",
  "roadCameraState.timestampEof": "ns",
  "driverCameraState.timestampSof": "ns",
  "driverCameraState.timestampEof": "ns",
  "wideRoadCameraState.timestampSof": "ns",
  "wideRoadCameraState.timestampEof": "ns",
  "carControl.actuators.torque": "ratio",
  "carControl.actuators.steeringAngleDeg": "deg",
  "carControl.actuators.accel": "m/s^2",
  "carControl.actuators.gas": "ratio",
  "carControl.actuators.brake": "ratio",
  "carControl.actuators.speed": "m/s",
  "carControl.actuators.jerk": "m/s^3",
  "carControl.actuators.aTarget": "m/s^2",
  "carOutput.actuatorsOutput.torque": "ratio",
  "carOutput.actuatorsOutput.steeringAngleDeg": "deg",
  "carOutput.actuatorsOutput.accel": "m/s^2",
  "carOutput.actuatorsOutput.gas": "ratio",
  "carOutput.actuatorsOutput.brake": "ratio",
  "carOutput.actuatorsOutput.speed": "m/s",
  "carOutput.actuatorsOutput.jerk": "m/s^3",
  "carOutput.actuatorsOutput.aTarget": "m/s^2",
  "longitudinalPlan.aTarget": "m/s^2",
  "longitudinalPlan.aTargetBase": "m/s^2",
  "longitudinalPlan.leadPreviewSeconds": "s",
  "longitudinalPlan.leadPreviewActionTime": "s",
  "longitudinalPlan.leadPreviewAccel": "m/s^2",
}
