#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "$DIR/launch_env.sh"

function cleanup_stale_git_lfs_hooks {
  # Some deployed checkouts still contain hooks installed by git-lfs even
  # though the executable is no longer part of the device image. Those hooks
  # make an otherwise successful pull/checkout fail at the final hook step.
  command -v git-lfs >/dev/null 2>&1 && return

  local git_dir
  local hook
  local hook_path

  git_dir="$(git -C "$DIR" rev-parse --absolute-git-dir 2>/dev/null || true)"
  [ -n "$git_dir" ] || return

  for hook in post-checkout post-commit post-merge pre-push; do
    hook_path="$git_dir/hooks/$hook"
    # Delete only hooks generated by git-lfs. Preserve every unrelated local
    # hook, including similarly named custom hooks.
    if [ -f "$hook_path" ] && grep -q "command -v git-lfs" "$hook_path" && grep -q "git lfs $hook" "$hook_path"; then
      echo "Removing stale git-lfs hook: $hook"
      rm -f -- "$hook_path"
    fi
  done
}

function ensure_python_package {
  local import_name="$1"
  local package_name="$2"
  local required="${3:-0}"
  local install_dependencies="${4:-0}"
  local wheel_dir="$DIR/third_party/wheels"

  if python3 -c "import ${import_name}" > /dev/null 2>&1; then
    echo "${package_name} already installed."
    return 0
  fi

  echo "${package_name} installing from local wheel."
  if [ "$install_dependencies" = "1" ]; then
    python3 -m pip install --no-index --find-links "$wheel_dir" --target "$PYDEPS" --upgrade "$package_name"
  else
    python3 -m pip install --no-index --no-deps --find-links "$wheel_dir" --target "$PYDEPS" --upgrade "$package_name"
  fi
  if [ "$?" = "0" ] && \
     python3 -c "import ${import_name}" > /dev/null 2>&1; then
    echo "${package_name} installed."
    return 0
  fi

  if [ "$required" = "1" ]; then
    echo "Required Python package ${package_name} is unavailable; not starting openpilot."
    return 1
  fi

  echo "Optional Python package ${package_name} is unavailable; continuing without it."
  return 0
}

function bootstrap_runtime_dependencies {
  if ! ensure_python_package serial pyserial 1 || \
     ! ensure_python_package msgpack msgpack 1 || \
     ! ensure_python_package aiohttp aiohttp 1 1 || \
     ! ensure_python_package "aiortc; import av; import pylibsrtp" "aiortc==1.14.0" 1 1 || \
     ! ensure_python_package psutil psutil 1 || \
     ! ensure_python_package crcmod crcmod-plus 1 || \
     ! ensure_python_package jsonrpc json-rpc 1 || \
     ! ensure_python_package qrcode qrcode 1; then
    return 1
  fi

  ensure_python_package brotli brotli 0
  ensure_python_package usb pyusb 0

  # AGNOS 19 follows current comma, which no longer includes the legacy Eigen
  # and libjpeg wrappers used by this branch's rednose and JPEG encoder. Keep
  # those native headers/libraries available from official offline wheels.
  if { [ -f /TICI ] || [ -f /AGNOS ]; } && \
     { ! ensure_python_package eigen eigen 1 || ! ensure_python_package libjpeg libjpeg 1; }; then
    return 1
  fi

  ensure_python_package shapely shapely 0
}

function show_agnos_update_failure {
  local reason="$1"
  local message

  printf -v message 'AGNOS update paused.\n\n%s\n\nOpen the recovery address shown above (port 6999).\nLog: /data/agnos-updater-ui.log\n\nTap Reboot to try the updater again.' "$reason"
  printf '%s\n' "$message"
  python3 "$DIR/openpilot/system/ui/text.py" "$message" || true
}

function agnos_init {
  # TODO: move this to agnos
  sudo rm -f /data/etc/NetworkManager/system-connections/*.nmmeta
  rm -f /data/scons_cache/config.lock

  sudo abctl --set_success

  # TODO: do this without udev in AGNOS
  # udev does this, but sometimes we startup faster
  sudo chgrp gpu /dev/adsprpc-smd /dev/ion /dev/kgsl-3d0
  sudo chmod 660 /dev/adsprpc-smd /dev/ion /dev/kgsl-3d0

  export AGNOS_UPDATE_CONFIRMATION_FILE="${AGNOS_UPDATE_CONFIRMATION_FILE:-/data/agnos-update-confirmed}"

  # Check if AGNOS update is required
  if [ "$(< /VERSION)" != "$AGNOS_VERSION" ]; then
    AGNOS_PY="$DIR/openpilot/system/hardware/tici/agnos.py"
    MANIFEST="$DIR/openpilot/system/hardware/tici/agnos.json"
    MODEL="$(tr -d '\000\r\n' 2>/dev/null < /sys/firmware/devicetree/base/model | tr '[:upper:]' '[:lower:]')"
    MODEL="${MODEL#comma }"
    if [ "$MODEL" = "c3" ] || [ "$MODEL" = "tici" ]; then
      MANIFEST="$DIR/openpilot/system/hardware/tici/agnos-tici.json"
    fi
    echo "AGNOS_PY=${AGNOS_PY}"
    echo "MANIFEST=${MANIFEST}"
    echo "MODEL=${MODEL}"

    # A completed inactive slot only needs activation and a reboot. Check this
    # before any network or standalone-UI dependency work.
    if python3 "$AGNOS_PY" --verify "$MANIFEST"; then
      echo "Verified AGNOS update activated; rebooting."
      if sudo reboot; then
        while true; do sleep 1; done
      fi
      show_agnos_update_failure "The updated slot is ready, but the reboot command failed."
      return 1
    fi

    if python3 -c "import jeepney" > /dev/null 2>&1; then
      echo "jeepney already installed."
    else
      echo "Installing the AGNOS updater UI dependency."
      if ! python3 -m pip install --target "$PYDEPS" --upgrade --timeout 15 --retries 2 jeepney; then
        show_agnos_update_failure "The updater UI dependency could not be installed. Check the network, then retry."
        return 1
      fi
    fi

    local AGNOS_UI_LOG="/data/agnos-updater-ui.log"
    local ui_result
    : > "$AGNOS_UI_LOG"
    for attempt in 1 2 3; do
      echo "Starting AGNOS updater UI (${attempt}/3)." | tee -a "$AGNOS_UI_LOG"
      python3 "$DIR/openpilot/system/ui/updater.py" "$AGNOS_PY" "$MANIFEST" 2>&1 | tee -a "$AGNOS_UI_LOG"
      ui_result=${PIPESTATUS[0]}
      echo "AGNOS updater UI exited with status ${ui_result}." | tee -a "$AGNOS_UI_LOG"
      sleep 2
    done

    show_agnos_update_failure "The updater UI stopped three times. No unconfirmed update was installed."
    return 1
  else
    rm -f "$AGNOS_UPDATE_CONFIRMATION_FILE"
  fi
}

function start_carrot_recovery {
  local recovery_script="$DIR/openpilot/selfdrive/carrot/recovery/server.py"
  local py_bin

  [ -f "$recovery_script" ] || return
  py_bin="$(command -v python3 || command -v python || true)"
  [ -n "$py_bin" ] || return

  if command -v pgrep >/dev/null 2>&1 && pgrep -f "openpilot/selfdrive/carrot/recovery/server.py" >/dev/null 2>&1; then
    return
  fi

  echo "Starting carrot recovery server on 6999."
  (cd "$DIR" && "$py_bin" "$recovery_script" --port 6999 >> /tmp/carrot_recovery.log 2>&1 &)
}

function start_carrot_web {
  export CARROT_WEB_EXTERNAL="${CARROT_WEB_EXTERNAL:-1}"
  [ "$CARROT_WEB_EXTERNAL" = "1" ] || return

  local watchdog_script="$DIR/scripts/carrot_web_watchdog.sh"
  local pid_file="${CARROT_WEB_PID_FILE:-/tmp/carrot_web_watchdog.pid}"
  local py_bin

  [ -f "$watchdog_script" ] || return

  # The watchdog survives tmux/openpilot restarts. The pid file can be lost or
  # replaced while that old process is still alive, so also check the process
  # table before starting another watchdog.
  if command -v pgrep >/dev/null 2>&1 && pgrep -f '[c]arrot_web_watchdog[.]sh' >/dev/null 2>&1; then
    return
  fi

  if [ -f "$pid_file" ]; then
    local old_pid
    old_pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [ -n "$old_pid" ] && kill -0 "$old_pid" >/dev/null 2>&1; then
      return
    fi
  fi

  py_bin="$(command -v python3 || command -v python || true)"
  [ -n "$py_bin" ] || return

  echo "Starting external carrot web server on 7000."
  if command -v setsid >/dev/null 2>&1; then
    setsid bash "$watchdog_script" "$DIR" "$py_bin" >> /tmp/carrot_server.log 2>&1 &
  else
    bash "$watchdog_script" "$DIR" "$py_bin" >> /tmp/carrot_server.log 2>&1 &
  fi
}

function invalidate_modeld_build_if_needed {
  local stamp_path="$DIR/openpilot/selfdrive/modeld/models/.build_stamp"
  local big_stamp_path="$DIR/openpilot/selfdrive/modeld/models/.big_model_build_stamp"
  local tg_devices_path="$DIR/openpilot/selfdrive/modeld/models/tg_input_devices.json"
  local driving_pkl_path="$DIR/openpilot/selfdrive/modeld/models/driving_tinygrad.pkl"
  local old_stamp
  local old_big_stamp

  MODEL_BUILD_STAMP_VALUE="$(git rev-parse HEAD:openpilot/selfdrive/modeld HEAD:tinygrad_repo HEAD:openpilot/common/file_chunker.py 2>/dev/null | tr '\n' ':')"
  if [ -z "$MODEL_BUILD_STAMP_VALUE" ]; then
    MODEL_BUILD_STAMP_VALUE="$(git rev-parse HEAD 2>/dev/null || true)"
  fi

  old_stamp="$(cat "$stamp_path" 2>/dev/null || true)"
  if [ "$MODEL_BUILD_STAMP_VALUE" != "$old_stamp" ] || [ ! -f "$tg_devices_path" ] || { [ ! -f "$driving_pkl_path" ] && [ ! -f "$driving_pkl_path.chunkmanifest" ]; }; then
    echo "Model/tinygrad inputs changed or artifacts are missing; revalidating with SCons."
    # Keep generated artifacts. SCons tracks the compiler, tinygrad and model
    # dependencies and will rebuild only stale targets. Deleting everything
    # here caused unrelated modeld changes to trigger long full recompiles.
    FORCE_REBUILD=1
  fi

  if [ -n "$BIG_MODEL_SHA" ]; then
    old_big_stamp="$(cat "$big_stamp_path" 2>/dev/null || true)"
    if [ "$BIG_MODEL_SHA" != "$old_big_stamp" ] || [ ! -f "${BIG_MODEL_PKL_PATH}.chunkmanifest" ]; then
      echo "USB eGPU big model changed or needs compilation."
      FORCE_REBUILD=1
    fi
  fi
}

function prepare_big_model_if_needed {
  BIG_MODEL_SHA=""
  BIG_MODEL_PKL_PATH=""

  # Only local state is consulted on the startup path. Remote model delivery
  # runs in the background below and must never delay manager startup.
  if ! python3 -c 'from openpilot.selfdrive.modeld.helpers import usbgpu_present; raise SystemExit(0 if usbgpu_present() else 1)' 2>/dev/null; then
    return
  fi

  BIG_MODEL_SHA="$(python3 -m openpilot.selfdrive.modeld.big_model --active-sha 2>/dev/null || true)"
  if [ -n "$BIG_MODEL_SHA" ]; then
    BIG_MODEL_PKL_PATH="$(python3 -c 'from openpilot.selfdrive.modeld.helpers import modeld_pkl_path; print(modeld_pkl_path(True))' 2>/dev/null || true)"
  fi

  # Do not reject compilation from a one-shot 12V check here. During ignition
  # startup the USB bridge can enumerate before switched GPU power and PCIe are
  # ready. Mark the missing target stale and let build_usbgpu_model perform its
  # retrying readiness check while the build screen remains visible.
}

function start_big_model_update {
  local log_path="/tmp/big_model_update.log"
  local lock_path="/tmp/big_model_update.lock"

  if command -v pgrep >/dev/null 2>&1 && pgrep -f '[o]penpilot.selfdrive.modeld.big_model --ensure-if-egpu' >/dev/null 2>&1; then
    return
  fi

  echo "Checking optional eGPU model in background (log: ${log_path})."
  if command -v flock >/dev/null 2>&1; then
    (
      exec 9>"$lock_path"
      flock -n 9 || exit 0
      if command -v ionice >/dev/null 2>&1; then
        PYTHONUNBUFFERED=1 ionice -c 3 nice -n 10 python3 -m openpilot.selfdrive.modeld.big_model --ensure-if-egpu --network-wait-seconds 60
      else
        PYTHONUNBUFFERED=1 nice -n 10 python3 -m openpilot.selfdrive.modeld.big_model --ensure-if-egpu --network-wait-seconds 60
      fi
    ) >> "$log_path" 2>&1 &
  else
    if command -v ionice >/dev/null 2>&1; then
      PYTHONUNBUFFERED=1 ionice -c 3 nice -n 10 python3 -m openpilot.selfdrive.modeld.big_model --ensure-if-egpu --network-wait-seconds 60 >> "$log_path" 2>&1 &
    else
      PYTHONUNBUFFERED=1 nice -n 10 python3 -m openpilot.selfdrive.modeld.big_model --ensure-if-egpu --network-wait-seconds 60 >> "$log_path" 2>&1 &
    fi
  fi
}

function invalidate_native_build_if_needed {
  local missing=0
  local path

  for path in "$DIR/openpilot/system/loggerd/loggerd" "$DIR/openpilot/system/loggerd/encoderd" "$DIR/openpilot/system/camerad/camerad"; do
    if [ ! -x "$path" ]; then
      echo "Missing native binary: $path"
      missing=1
    fi
  done

  if [ "$missing" = "1" ]; then
    FORCE_REBUILD=1
  fi
}

function launch {
  cleanup_stale_git_lfs_hooks

  # Remove orphaned git lock if it exists on boot
  [ -f "$DIR/.git/index.lock" ] && rm -f $DIR/.git/index.lock

  # Check to see if there's a valid overlay-based update available. Conditions
  # are as follows:
  #
  # 1. The DIR init file has to exist, with a newer modtime than anything in
  #    the DIR Git repo. This checks for local development work or the user
  #    switching branches/forks, which should not be overwritten.
  # 2. The FINALIZED consistent file has to exist, indicating there's an update
  #    that completed successfully and synced to disk.

  if [ -f "${DIR}/.overlay_init" ]; then
    find ${DIR}/.git -newer ${DIR}/.overlay_init | grep -q '.' 2> /dev/null
    if [ $? -eq 0 ]; then
      echo "${DIR} has been modified, skipping overlay update installation"
    else
      if [ -f "${STAGING_ROOT}/finalized/.overlay_consistent" ]; then
        if [ ! -d /data/safe_staging/old_openpilot ]; then
          echo "Valid overlay update found, installing"
          LAUNCHER_LOCATION="${BASH_SOURCE[0]}"

          mv $DIR /data/safe_staging/old_openpilot
          mv "${STAGING_ROOT}/finalized" $DIR
          cd $DIR

          echo "Restarting launch script ${LAUNCHER_LOCATION}"
          unset AGNOS_VERSION
          exec "${LAUNCHER_LOCATION}"
        else
          echo "openpilot backup found, not updating"
          # TODO: restore backup? This means the updater didn't start after swapping
        fi
      fi
    fi
  fi

  # handle pythonpath
  ln -sfn $(pwd) /data/pythonpath
  PYDEPS="$DIR/pydeps"
  mkdir -p "$PYDEPS"
  export PYTHONPATH="$PYDEPS:$PWD${PYTHONPATH:+:$PYTHONPATH}"

  # Keep recovery access available even when an OS update or source build fails.
  if [ ! -f /data/params/d/GithubSshKeys ]; then
    echo -n openpilot > /data/params/d/GithubUsername
    cat /usr/comma/setup_keys > /data/params/d/GithubSshKeys
  fi
  if [ "$(cat /data/params/d/SshEnabled 2>/dev/null)" != "1" ]; then
    echo -n 1 > /data/params/d/SshEnabled
  fi
  start_carrot_recovery

  # hardware specific init
  if [ -f /AGNOS ]; then
    if ! agnos_init; then
      while true; do sleep 1; done
    fi
  fi

  # AGNOS must be current before installing its matching offline wheels. SCons
  # imports native dependency modules while building Params, so bootstrap them
  # before the first SCons invocation.
  if ! bootstrap_runtime_dependencies; then
    while true; do sleep 1; done
  fi

  # Build Params before any long-running carrot service imports it.
  if ! bash "$DIR/scripts/ensure_params_build.sh"; then
    echo "Params registry build failed, not starting openpilot."
    while true; do sleep 1; done
  fi

  start_carrot_web


  FORCE_REBUILD=0
  prepare_big_model_if_needed
  invalidate_modeld_build_if_needed
  invalidate_native_build_if_needed

  rm -f openpilot/selfdrive/pandad/*.so
  # write tmux scrollback to a file
  tmux capture-pane -pq -S-1500 > /tmp/launch_log

  # start manager
  cd openpilot/system/manager
  if [ "$FORCE_REBUILD" = "1" ] || [ ! -f $DIR/prebuilt ]; then
    if ! ./build.py; then
      echo "openpilot build failed, not starting manager."
      while true; do sleep 1; done
    fi
    if [ "$FORCE_REBUILD" = "1" ]; then
      mkdir -p "$DIR/openpilot/selfdrive/modeld/models"
      echo -n "$MODEL_BUILD_STAMP_VALUE" > "$DIR/openpilot/selfdrive/modeld/models/.build_stamp"
      if [ -n "$BIG_MODEL_SHA" ] && [ -f "${BIG_MODEL_PKL_PATH}.chunkmanifest" ]; then
        echo -n "$BIG_MODEL_SHA" > "$DIR/openpilot/selfdrive/modeld/models/.big_model_build_stamp"
      fi
    fi
  fi
  start_big_model_update
  ./manager.py

  # if broken, keep on screen error
  while true; do sleep 1; done
}

launch
