"""Independent wire fixtures based on upstream 24e8917's Swift Session/Wire.

Socket tests exercise real framing and client code; the fixture substitutes
model execution only. They do not establish mobile NPU parity or USB timing.
"""
from dataclasses import replace
import hashlib
import json
import socket
import struct
import threading
from types import SimpleNamespace as NS

import numpy as np
import pytest

from openpilot.selfdrive.modeld.jetlink import compat, link, mac
from jetlink import protocol as V2, protocol_v3 as V3
from jetlink.client import JetlinkClient
from jetlink.transport.base import LinkError, StreamTransport
from jetlink.transport.tcp import TcpTransport


class MemoryStream(StreamTransport):
  def __init__(self, version=2, incoming=b'', gadget=False):
    super().__init__()
    self.wire_protocol = V2 if version == 2 else V3
    self.incoming = bytearray(incoming)
    self.out = bytearray()
    self.closed = False
    self.tx_align = 16384 if gadget else 0

  def _write(self, bufs):
    data = b''.join(bufs)
    self.out.extend(data)
    return len(data)

  def _read_into(self, dest, timeout):
    n = min(len(dest), len(self.incoming), 173)  # fragmented stream
    dest[:n] = self.incoming[:n]
    del self.incoming[:n]
    return n

  def close(self):
    self.closed = True


def packet(version, kind, seq, payload=b'', gadget=False):
  # Deliberately independent of the client's protocol and transport helpers.
  multiple = 1024 if version == 2 else 512
  size = 32 + len(payload)
  flags = 0 if gadget or size % multiple else 128
  pad = (-size % 16384) if gadget else bool(flags)
  return struct.pack('<IHHIIIQ4x', 0x4B4E4C4A, version, kind, seq, flags, len(payload), 0) + payload + bytes(pad)


@pytest.mark.parametrize('version', [2, 3])
@pytest.mark.parametrize('length', [0, 1, 480, 992, 16352, 20000])
@pytest.mark.parametrize('gadget', [False, True])
def test_framing_matches_independent_header_padding_and_fragmentation(version, length, gadget):
  data = bytes(i % 251 for i in range(length))
  tx = MemoryStream(version, gadget=gadget)
  tx.send(8, 7, [data] if data else [])
  assert bytes(tx.out) == packet(version, 8, 7, data, gadget)
  rx = MemoryStream(version, incoming=bytes(tx.out) + packet(version, 15, 8, gadget=gadget))
  rx.rx_align = 16384 if gadget else 0
  msg = rx.recv(.3)
  assert (msg.msg_type, msg.seq, bytes(msg.payload)) == (8, 7, data)
  assert rx.recv(.3).seq == 8


@pytest.mark.parametrize('ours,theirs', [(2, 3), (3, 2), (3, 4)])
def test_wrong_version_latches_desync(ours, theirs):
  stream = MemoryStream(ours, packet(theirs, 2, 1, b'{}'))
  with pytest.raises(LinkError, match='protocol'):
    stream.recv(.1)
  with pytest.raises(LinkError, match='desynced'):
    stream.recv(.1)


def test_default_v2_and_v3_sessions_are_independent():
  a, b = MemoryStream(), MemoryStream(3)
  for _ in range(3):
    a.send(15, 1)
    b.send(15, 1)
  assert a.out == packet(2, 15, 1) * 3
  assert b.out == packet(3, 15, 1) * 3
  assert V2.VERSION == 2 and StreamTransport.wire_protocol is V2


def test_hello_retries_other_version_only_on_new_session_then_sticks():
  attempts = compat.ProtocolAttempts()
  failed = MemoryStream(incoming=packet(3, 2, 1, b'{"protocol":3}'))
  with pytest.raises(LinkError):
    attempts.hello(failed)
  assert failed.closed and attempts.version == 3
  for _ in range(2):
    stream = MemoryStream(incoming=packet(3, 2, 1, b'{"protocol":3}'))
    client, peer = attempts.hello(stream)
    assert isinstance(client, compat.V3Client) and peer['protocol'] == 3
    assert struct.unpack_from('<H', stream.out, 4)[0] == 3
    client.close()
  attempts.reset()
  stream = MemoryStream(incoming=packet(2, 2, 1, b'{"protocol":2}'))
  client, _ = attempts.hello(stream)
  assert type(client) is JetlinkClient and attempts.version == 2


@pytest.mark.parametrize('hello', [b'{"protocol":true}', b'{"protocol":3}', b'[]', b'{}', b'bad json'])
def test_hello_metadata_cannot_override_strict_header(hello):
  stream = MemoryStream(incoming=packet(2, 2, 1, hello))
  with pytest.raises((LinkError, ValueError)):
    compat.ProtocolAttempts().hello(stream)
  assert stream.closed


def test_v3_request_omits_previous_features_preserves_scalars_and_resets():
  stream = MemoryStream(3, gadget=True)
  client = compat.V3Client(stream)
  client.spec = link.SPEC
  packed = np.arange(link.SPEC.packed_nelem, dtype=np.float32)
  images = np.zeros(link.SPEC.warped_shape, dtype=np.uint8)
  client.infer_begin(images, packed, 42, reset=True, want_state=True)
  expected = struct.pack('<II', 42, 7) + images.tobytes() + packed[:12].tobytes()
  assert stream.out == packet(3, 8, 1, expected, gadget=True)
  assert len(stream.out) == 409600


def test_request_and_response_match_unmodified_upstream_v3_client_vectors():
  # Generated by executing upstream JetlinkClient(want_hidden=True),
  # 24e8917673829cbe1d146735956e9038cc93f227, on the pinned Cinque v2 spec.
  output = np.arange(link.SPEC.output_nelem, dtype=np.float32)
  response = struct.pack('<IIIII', 42, 0, 1, 2, 3) + output.tobytes() + b'{"temp_c":45}'
  stream = MemoryStream(3, incoming=packet(3, 9, 1, response))
  client = compat.V3Client(stream)
  client.spec = link.SPEC
  client.infer_begin(np.arange(link.SPEC.warped_nbytes, dtype=np.uint8).reshape(link.SPEC.warped_shape),
                     np.arange(link.SPEC.packed_nelem, dtype=np.float32), 42, reset=True, want_state=True)
  size = struct.unpack_from('<I', stream.out, 16)[0]
  assert size == 393272
  assert hashlib.sha256(stream.out[32:32+size]).hexdigest() == '08c60210be3ac59afb5f19059fa3042cb7efe55682c9233112146c8af6ec5930'
  result = client.infer_end(1)
  assert hashlib.sha256(result.tobytes()).hexdigest() == '90dbeb1879dfce449d959cf618847e526cfc21e1b299544a0d0aee440ee42bce'


@pytest.mark.parametrize('failure', ['short', 'compact', 'frame', 'status', 'nan', 'extra', 'telemetry', 'timeout'])
def test_v3_rejects_bad_frame_and_abandons_session(failure):
  output = np.arange(link.SPEC.output_nelem, dtype=np.float32)
  payload = struct.pack('<IIIII', 99 if failure == 'frame' else 1, 3 if failure == 'status' else 0, 1, 2, 3)
  if failure == 'nan':
    output[0] = np.nan
  payload += output.tobytes()
  if failure == 'short': payload = payload[:10]
  if failure == 'compact': payload = payload[:20+2068*4]
  if failure == 'extra': payload += b'{}'
  if failure == 'telemetry': payload += b'[]'
  stream = MemoryStream(3, incoming=packet(3, 9, 1, payload) if failure != 'timeout' else b'')
  client = compat.V3Client(stream, deadline=.02)
  client.spec = link.SPEC
  client.infer_begin(np.zeros(link.SPEC.warped_shape, np.uint8), np.zeros(link.SPEC.packed_nelem, np.float32), 1,
                     want_state=failure == 'telemetry')
  with pytest.raises(LinkError):
    client.infer_end(1)
  assert client.dead
  with pytest.raises(LinkError, match='previously failed'):
    client.infer_begin(np.zeros(link.SPEC.warped_shape, np.uint8), np.zeros(link.SPEC.packed_nelem, np.float32))


def test_v3_real_socket_upload_model_check_frames_telemetry_and_reset(tmp_path, monkeypatch):
  body = b'fixture-model-not-real-onnx' * 100
  spec = replace(link.SPEC, sha256=hashlib.sha256(body).hexdigest(), nbytes=len(body))
  for module in (compat, mac, link):
    monkeypatch.setattr(module, 'SPEC', spec)
  path = tmp_path/'model.onnx'
  path.write_bytes(body)
  monkeypatch.setattr(mac, 'model_file', lambda *a: path)
  errors, upload, resets = [], bytearray(), []
  a, b = socket.socketpair()
  a.settimeout(2)
  b.settimeout(2)

  def read(n):
    result = bytearray()
    while len(result) < n:
      chunk = b.recv(n-len(result))
      if not chunk: raise EOFError
      result.extend(chunk)
    return bytes(result)

  def host():
    # Raw socket peer follows the Swift wire contract, not our client codec.
    hidden = 0
    try:
      while True:
        magic, version, kind, seq, flags, size, reserved = struct.unpack('<IHHIIIQ4x', read(32))
        assert (magic, version, reserved) == (0x4B4E4C4A, 3, 0)
        payload = read(size)
        if flags & 128: read(1)
        if kind == 1:
          response = {'protocol': 3, 'backend': 'ort', 'device': 'qnn-phone', 'loaded': None}
          b.sendall(packet(3, 2, seq, json.dumps(response).encode()))
        elif kind == 3:
          assert json.loads(payload)['sha256'] == spec.sha256
          response = {'state': 'ready', 'spec': spec.to_dict()} if upload else {'state': 'need_upload', 'chunk': 128}
          b.sendall(packet(3, 4, seq, json.dumps(response).encode()))
        elif kind == 5:
          assert int.from_bytes(payload[:8], 'little') == len(upload)
          upload.extend(payload[8:])
        elif kind == 6:
          assert bytes(upload) == body
          b.sendall(packet(3, 4, seq, json.dumps({'state': 'ready', 'spec': spec.to_dict()}).encode()))
        elif kind == 8:
          assert len(payload) == 8 + spec.warped_nbytes + 48
          frame, flags = struct.unpack_from('<II', payload)
          assert flags & 4  # WANT_HIDDEN: never confuse compact/full output
          if flags & 1: hidden = 0
          hidden += 1
          resets.append(hidden)
          output = np.full(spec.output_nelem, hidden, np.float32)
          response = struct.pack('<IIIII', frame, 0, 100, 20, 130) + output.tobytes()
          if flags & 2: response += b'{"temp_c":45}'
          b.sendall(packet(3, 9, seq, response))
        else:
          raise AssertionError(kind)
    except EOFError:
      pass
    except BaseException as exc:
      errors.append(exc)
    finally:
      b.close()

  class Desktop(TcpTransport):
    def _write(self, bufs):
      self._set_timeout(self._write_timeout())
      return self.sock.send(b''.join(bufs))

  worker = threading.Thread(target=host, daemon=True)
  worker.start()
  attempts = compat.ProtocolAttempts()
  attempts.version = 3
  client, peer = attempts.hello(Desktop(a))
  try:
    mac.prepare(client, peer, lambda: True, lambda: True, lambda *a: None, tmp_path)
    for frame, reset in enumerate([True, False, True], 1):
      result = client.infer(np.zeros(spec.warped_shape, np.uint8), np.zeros(spec.packed_nelem, np.float32),
                            frame, reset=reset, want_state=True)
      np.testing.assert_array_equal(result, 2 if frame == 2 else 1)
      assert client.last_timings == (100, 20, 130)
      assert client.last_state == {'temp_c': 45}
  finally:
    client.close()
    worker.join(3)
  assert not worker.is_alive() and not errors and resets == [1, 2, 1]


def test_unprepared_v3_phone_cannot_provision_onroad():
  with pytest.raises(mac.PreparationDeferred, match='ignition off'):
    mac.prepare(NS(ensure_engine=lambda *a, **kw: pytest.fail('onroad preparation')),
                {'protocol': 3}, lambda: False, lambda: True, lambda *a: None)


@pytest.mark.parametrize('mismatch', ['sha256', 'checkpoint', 'output_slices', 'frame_skip'])
def test_v3_prepared_model_must_match_entire_pinned_contract(mismatch):
  spec = link.SPEC.to_dict()
  if mismatch == 'output_slices':
    spec[mismatch]['plan'][0] += 1
  else:
    spec[mismatch] = 3 if mismatch == 'frame_skip' else 'wrong-model'
  stream = MemoryStream(3, incoming=packet(3, 4, 1, json.dumps({'state': 'ready', 'spec': spec}).encode()))
  client = compat.V3Client(stream)
  with pytest.raises((LinkError, ValueError)):
    mac.prepare(client, {'protocol': 3, 'loaded': link.SPEC.sha256}, lambda: False, lambda: True, lambda *a: None)


def test_loaded_v3_phone_reconnects_onroad_without_upload():
  stream = MemoryStream(3, incoming=packet(3, 4, 1, json.dumps({'state': 'ready', 'spec': link.SPEC.to_dict()}).encode()))
  client = compat.V3Client(stream)
  mac.prepare(client, {'protocol': 3, 'loaded': link.SPEC.sha256}, lambda: False, lambda: True, lambda *a: None)
  assert client.spec.to_dict() == link.SPEC.to_dict()
