#pragma once

#include <string>
#include <unordered_map>

inline static std::unordered_map<std::string, uint32_t> keys = {
    {"AccessToken", CLEAR_ON_MANAGER_START | DONT_LOG},
    {"AdbEnabled", PERSISTENT},
    {"AlwaysOnDM", PERSISTENT},
    {"ApiCache_Device", PERSISTENT},
    {"ApiCache_FirehoseStats", PERSISTENT},
    {"AssistNowToken", PERSISTENT},
    {"AthenadPid", PERSISTENT},
    {"AthenadUploadQueue", PERSISTENT},
    {"AthenadRecentlyViewedRoutes", PERSISTENT},
    {"BootCount", PERSISTENT},
    {"CalibrationParams", PERSISTENT},
    {"CameraDebugExpGain", CLEAR_ON_MANAGER_START},
    {"CameraDebugExpTime", CLEAR_ON_MANAGER_START},
    {"CarBatteryCapacity", PERSISTENT},
    {"CarParams", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"CarParamsCache", CLEAR_ON_MANAGER_START},
    {"CarParamsPersistent", PERSISTENT},
    {"CarParamsPrevRoute", PERSISTENT},
    {"CompletedTrainingVersion", PERSISTENT},
    {"ControlsReady", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"CurrentBootlog", PERSISTENT},
    {"CurrentRoute", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"DisableLogging", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"DisablePowerDown", PERSISTENT},
    {"DisableUpdates", PERSISTENT},
    {"DisengageOnAccelerator", PERSISTENT},
    {"DongleId", PERSISTENT},
    {"DoReboot", CLEAR_ON_MANAGER_START},
    {"DoShutdown", CLEAR_ON_MANAGER_START},
    {"DoUninstall", CLEAR_ON_MANAGER_START},
    {"AlphaLongitudinalEnabled", PERSISTENT | DEVELOPMENT_ONLY},
    {"ExperimentalMode", PERSISTENT},
    {"ExperimentalModeConfirmed", PERSISTENT},
    {"FirmwareQueryDone", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"ForcePowerDown", PERSISTENT},
    {"GitBranch", PERSISTENT},
    {"GitCommit", PERSISTENT},
    {"GitCommitDate", PERSISTENT},
    {"GitDiff", PERSISTENT},
    {"GithubSshKeys", PERSISTENT},
    {"GithubUsername", PERSISTENT},
    {"GitRemote", PERSISTENT},
    {"GsmApn", PERSISTENT},
    {"GsmMetered", PERSISTENT},
    {"GsmRoaming", PERSISTENT},
    {"HardwareSerial", PERSISTENT},
    {"HasAcceptedTerms", PERSISTENT},
    {"InstallDate", PERSISTENT},
    {"IsDriverViewEnabled", CLEAR_ON_MANAGER_START},
    {"IsEngaged", PERSISTENT},
    {"IsLdwEnabled", PERSISTENT},
    {"IsMetric", PERSISTENT},
    {"IsOffroad", CLEAR_ON_MANAGER_START},
    {"IsOnroad", PERSISTENT},
    {"IsRhdDetected", PERSISTENT},
    {"IsReleaseBranch", CLEAR_ON_MANAGER_START},
    {"IsTakingSnapshot", CLEAR_ON_MANAGER_START},
    {"IsTestedBranch", CLEAR_ON_MANAGER_START},
    {"JoystickDebugMode", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LanguageSetting", PERSISTENT},
    {"LastAthenaPingTime", CLEAR_ON_MANAGER_START},
    {"LastGPSPosition", PERSISTENT},
    {"LastManagerExitReason", CLEAR_ON_MANAGER_START},
    {"LastOffroadStatusPacket", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LastPowerDropDetected", CLEAR_ON_MANAGER_START},
    {"LastUpdateException", CLEAR_ON_MANAGER_START},
    {"LastUpdateTime", PERSISTENT},
    {"LiveDelay", PERSISTENT},
    {"LiveParameters", PERSISTENT},
    {"LiveParametersV2", PERSISTENT},
    {"LiveTorqueParameters", PERSISTENT | DONT_LOG},
    {"LocationFilterInitialState", PERSISTENT},
    {"LongitudinalManeuverMode", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LongitudinalPersonality", PERSISTENT},
    {"NetworkMetered", PERSISTENT},
    {"ObdMultiplexingChanged", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"ObdMultiplexingEnabled", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_BadNvme", CLEAR_ON_MANAGER_START},
    {"Offroad_CarUnrecognized", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_ConnectivityNeeded", CLEAR_ON_MANAGER_START},
    {"Offroad_ConnectivityNeededPrompt", CLEAR_ON_MANAGER_START},
    {"Offroad_IsTakingSnapshot", CLEAR_ON_MANAGER_START},
    {"Offroad_NeosUpdate", CLEAR_ON_MANAGER_START},
    {"Offroad_NoFirmware", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_Recalibration", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_StorageMissing", CLEAR_ON_MANAGER_START},
    {"Offroad_TemperatureTooHigh", CLEAR_ON_MANAGER_START},
    {"Offroad_UnofficialHardware", CLEAR_ON_MANAGER_START},
    {"Offroad_UpdateFailed", CLEAR_ON_MANAGER_START},
    {"OpenpilotEnabledToggle", PERSISTENT},
    {"PandaHeartbeatLost", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"PandaSomResetTriggered", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"PandaSignatures", CLEAR_ON_MANAGER_START},
    {"PrimeType", PERSISTENT},
    {"RecordFront", PERSISTENT},
    {"RecordFrontLock", PERSISTENT},  // for the internal fleet
    {"SecOCKey", PERSISTENT | DONT_LOG},
    {"RouteCount", PERSISTENT},
    {"SnoozeUpdate", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"SshEnabled", PERSISTENT},
    {"TermsVersion", PERSISTENT},
    {"TrainingVersion", PERSISTENT},
    {"UbloxAvailable", PERSISTENT},
    {"UpdateAvailable", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"UpdateFailedCount", CLEAR_ON_MANAGER_START},
    {"UpdaterAvailableBranches", PERSISTENT},
    {"UpdaterCurrentDescription", CLEAR_ON_MANAGER_START},
    {"UpdaterCurrentReleaseNotes", CLEAR_ON_MANAGER_START},
    {"UpdaterFetchAvailable", CLEAR_ON_MANAGER_START},
    {"UpdaterNewDescription", CLEAR_ON_MANAGER_START},
    {"UpdaterNewReleaseNotes", CLEAR_ON_MANAGER_START},
    {"UpdaterState", CLEAR_ON_MANAGER_START},
    {"UpdaterTargetBranch", CLEAR_ON_MANAGER_START},
    {"UpdaterLastFetchTime", PERSISTENT},
    {"Version", PERSISTENT},

    // carrot
    {"LongitudinalPersonalityMax", PERSISTENT},
    {"NetworkAddress", CLEAR_ON_MANAGER_START},

    {"ApiCache_NavDestinations", PERSISTENT},
    {"NavDestination", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"NavDestinationWaypoints", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"NavPastDestinations", PERSISTENT},
    {"NavSettingLeftSide", PERSISTENT},
    {"NavSettingTime24h", PERSISTENT},
    {"MapboxStyle", PERSISTENT },
    {"MapboxPublicKey", PERSISTENT},
    {"MapboxSecretKey", PERSISTENT},
    {"GMapKey", PERSISTENT},
    {"SearchInput", PERSISTENT},

    {"CarSelected3", PERSISTENT},
    {"SupportedCars", PERSISTENT},
    {"SupportedCars_gm", PERSISTENT},
    {"ShowDebugUI", PERSISTENT},
    {"ShowTpms", PERSISTENT},
    {"ShowDateTime", PERSISTENT},
    {"ShowPathEnd", PERSISTENT},
    {"ShowCustomBrightness", PERSISTENT},
    {"ShowLaneInfo", PERSISTENT},
    {"ShowRadarInfo", PERSISTENT},
    {"ShowDeviceState", PERSISTENT},
    {"ShowRouteInfo", PERSISTENT },
    {"ShowPathMode", PERSISTENT},
    {"ShowPathColor", PERSISTENT},
    {"ShowPathModeCruiseOff", PERSISTENT},
    {"ShowPathColorCruiseOff", PERSISTENT},
    {"ShowPathModeLane", PERSISTENT},
    {"ShowPathColorLane", PERSISTENT},
    {"ShowPlotMode", PERSISTENT},
    {"RecordRoadCam", PERSISTENT },
    {"HDPuse", PERSISTENT },

    {"AutoCruiseControl", PERSISTENT},
    {"CruiseEcoControl", PERSISTENT},
    {"CarrotCruiseDecel", PERSISTENT},
    {"CarrotCruiseAtcDecel", PERSISTENT},
    {"AutoGasTokSpeed", PERSISTENT},
    {"AutoGasSyncSpeed", PERSISTENT},
    {"AutoEngage", PERSISTENT},
    {"DisableMinSteerSpeed", PERSISTENT},
    {"AutoCurveSpeedLowerLimit", PERSISTENT},
    {"AutoCurveSpeedFactor", PERSISTENT},
    {"AutoCurveSpeedAggressiveness", PERSISTENT},
    {"AutoTurnControl", PERSISTENT},
    {"AutoTurnControlSpeedTurn", PERSISTENT},
    {"AutoTurnControlTurnEnd", PERSISTENT},
    {"AutoTurnMapChange", PERSISTENT },
    {"AutoNaviSpeedCtrlEnd", PERSISTENT},
    {"AutoNaviSpeedCtrlMode", PERSISTENT},
    {"AutoRoadSpeedLimitOffset", PERSISTENT},
    {"AutoNaviSpeedBumpTime", PERSISTENT},
    {"AutoNaviSpeedBumpSpeed", PERSISTENT},
    {"AutoNaviSpeedDecelRate", PERSISTENT},
    {"AutoNaviSpeedSafetyFactor", PERSISTENT},
    {"AutoNaviCountDownMode", PERSISTENT},
    {"TurnSpeedControlMode", PERSISTENT},
    {"MapTurnSpeedFactor", PERSISTENT},
    {"StoppingAccel", PERSISTENT},
    {"AutoSpeedUptoRoadSpeedLimit", PERSISTENT},
    {"AutoRoadSpeedAdjust", PERSISTENT},
    {"StopDistanceCarrot", PERSISTENT},
    {"ComfortBrake", PERSISTENT},
    {"JLeadFactor3", PERSISTENT},
    {"CruiseButtonMode", PERSISTENT},
    {"LfaButtonMode", PERSISTENT},
    {"CruiseButtonTest1", PERSISTENT},
    {"CruiseButtonTest2", PERSISTENT},
    {"CruiseButtonTest3", PERSISTENT},
    {"CruiseSpeedUnit", PERSISTENT},
    {"CruiseSpeed1", PERSISTENT},
    {"CruiseSpeed2", PERSISTENT},
    {"CruiseSpeed3", PERSISTENT},
    {"CruiseSpeed4", PERSISTENT},
    {"CruiseSpeed5", PERSISTENT},
    {"PaddleMode", PERSISTENT},
    {"MyDrivingMode", PERSISTENT},
    {"MyDrivingModeAuto", PERSISTENT},
    {"TrafficLightDetectMode", PERSISTENT},
    {"SteerActuatorDelay", PERSISTENT},
    {"CruiseOnDist", PERSISTENT},
    {"CruiseMaxVals0", PERSISTENT},
    {"CruiseMaxVals1", PERSISTENT},
    {"CruiseMaxVals2", PERSISTENT},
    {"CruiseMaxVals3", PERSISTENT},
    {"CruiseMaxVals4", PERSISTENT},
    {"CruiseMaxVals5", PERSISTENT},
    {"CruiseMaxVals6", PERSISTENT},
    {"LongTuningKpV", PERSISTENT},
    {"LongTuningKiV", PERSISTENT},
    {"LongTuningKf", PERSISTENT},
    {"LongActuatorDelay", PERSISTENT },
    {"VEgoStopping", PERSISTENT },
    {"RadarReactionFactor", PERSISTENT},
    {"EnableRadarTracks", PERSISTENT},
    {"EnableCornerRadar", PERSISTENT},
    {"EnableRadarTracksResult", PERSISTENT | CLEAR_ON_MANAGER_START},
    {"CanParserResult", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION },
    {"HotspotOnBoot", PERSISTENT},
    {"SoftwareMenu", PERSISTENT},
    {"HyundaiCameraSCC", PERSISTENT},
    {"IsLdwsCar", PERSISTENT},
    {"CanfdHDA2", PERSISTENT},
    {"CanfdDebug", PERSISTENT},
    {"SoundVolumeAdjust", PERSISTENT},
    {"SoundVolumeAdjustEngage", PERSISTENT},
    {"TFollowGap1", PERSISTENT},
    {"TFollowGap2", PERSISTENT},
    {"TFollowGap3", PERSISTENT},
    {"TFollowGap4", PERSISTENT},
    {"DynamicTFollow", PERSISTENT},
    {"DynamicTFollowLC", PERSISTENT},
    {"HapticFeedbackWhenSpeedCamera", PERSISTENT},
    {"UseLaneLineSpeed", PERSISTENT},
    {"UseLaneLineCurveSpeed", PERSISTENT},
    {"AdjustLaneOffset", PERSISTENT},
    {"LaneChangeNeedTorque", PERSISTENT},
    {"LaneChangeDelay", PERSISTENT },
    {"LaneChangeBsd", PERSISTENT},
    {"MaxAngleFrames", PERSISTENT},
    {"SoftHoldMode", PERSISTENT},
    {"LatMpcPathCost", PERSISTENT},
    {"LatMpcMotionCost", PERSISTENT},
    {"LatMpcAccelCost", PERSISTENT},
    {"LatMpcJerkCost", PERSISTENT},
    {"LatMpcSteeringRateCost", PERSISTENT },
    {"LatMpcInputOffset", PERSISTENT},
    {"LatMpcOutputOffset", PERSISTENT},
    {"PathOffset", PERSISTENT},
    {"LateralTorqueCustom", PERSISTENT},
    {"LateralTorqueAccelFactor", PERSISTENT},
    {"LateralTorqueFriction", PERSISTENT},
    {"LateralTorqueKpV", PERSISTENT},
    {"LateralTorqueKiV", PERSISTENT},
    {"LateralTorqueKf", PERSISTENT},
    {"LateralTorqueKd", PERSISTENT},
    {"CustomSteerMax", PERSISTENT},
    {"CustomSteerDeltaUp", PERSISTENT},
    {"CustomSteerDeltaDown", PERSISTENT},
    {"CustomSteerDeltaUpLC", PERSISTENT},
    {"CustomSteerDeltaDownLC", PERSISTENT},
    {"SpeedFromPCM", PERSISTENT},
    {"MaxTimeOffroadMin", PERSISTENT},
    {"DisableDM", PERSISTENT},
    {"EnableConnect", PERSISTENT},
    {"MuteDoor", PERSISTENT},
    {"MuteSeatbelt", PERSISTENT},
    {"CarrotException", CLEAR_ON_MANAGER_START},
    {"CarName", PERSISTENT},
    {"EVTable", PERSISTENT},
    {"LongPitch", PERSISTENT},
    {"ActivateCruiseAfterBrake", CLEAR_ON_MANAGER_START},   // for GM autoResume
    {"CustomSR", PERSISTENT},
    {"SteerRatioRate", PERSISTENT},
    {"SoftRestartTriggered", CLEAR_ON_MANAGER_START},

    {"DevicePosition", CLEAR_ON_MANAGER_START},
};
