import { build } from "esbuild";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DRIVE_CONTENT_FACTORY_IDS } from "./src/features/drive/factory_catalog.js";
import { validateDriveContentCatalog } from "./src/features/drive/core/registry.js";

const buildFile = fileURLToPath(import.meta.url);
const webRoot = dirname(buildFile);

export const driveContentCatalogDefinition = Object.freeze({
  source: "src/features/drive/core/content_catalog.json",
  factoryIds: DRIVE_CONTENT_FACTORY_IDS,
});

export const bundleDefinitions = Object.freeze([
  Object.freeze({
    id: "app.asset-url",
    kind: "bundle",
    entry: "src/entries/app.js",
    output: "js/generated/app.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/app.js instead. */",
  }),
  Object.freeze({
    id: "drive.runtime",
    kind: "bundle",
    entry: "src/entries/drive.js",
    output: "js/generated/drive.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/drive.js instead. */",
  }),
  Object.freeze({
    id: "replay.runtime",
    kind: "bundle",
    entry: "src/entries/replay.js",
    output: "js/generated/replay.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/replay.js instead. */",
  }),
  Object.freeze({
    id: "settings.store",
    kind: "bundle",
    entry: "src/entries/settings.js",
    output: "js/generated/settings.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/settings.js instead. */",
  }),
  Object.freeze({
    id: "tools.runtime",
    kind: "bundle",
    entry: "src/entries/tools.js",
    output: "js/generated/tools.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/tools.js instead. */",
  }),
  Object.freeze({
    id: "logs.runtime",
    kind: "bundle",
    entry: "src/entries/logs.js",
    output: "js/generated/logs.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/logs.js instead. */",
  }),
  Object.freeze({
    id: "terminal.runtime",
    kind: "bundle",
    entry: "src/entries/terminal.js",
    output: "js/generated/terminal.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal.js instead. */",
  }),
  Object.freeze({
    id: "terminal.shared",
    kind: "bundle",
    entry: "src/entries/terminal_shared.js",
    output: "js/generated/terminal-shared.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal_shared.js instead. */",
  }),
  Object.freeze({
    id: "terminal.support",
    kind: "bundle",
    entry: "src/entries/terminal_support.js",
    output: "js/generated/terminal-support.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal_support.js instead. */",
  }),
  Object.freeze({
    id: "terminal.guest",
    kind: "bundle",
    entry: "src/entries/terminal_guest.js",
    output: "js/generated/terminal-guest.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal_guest.js instead. */",
  }),
  Object.freeze({
    id: "intro.runtime",
    kind: "bundle",
    entry: "src/entries/intro.js",
    output: "js/generated/intro.js",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/intro.js instead. */",
  }),
  Object.freeze({
    id: "design-tokens.styles",
    kind: "bundle",
    entry: "src/entries/design_tokens.css",
    output: "css/generated/design-tokens.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/design_tokens.css instead. */",
  }),
  Object.freeze({
    id: "design-system.styles",
    kind: "bundle",
    entry: "src/entries/design_system.css",
    output: "css/generated/design-system.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/design_system.css instead. */",
  }),
  Object.freeze({
    id: "drive.styles",
    kind: "bundle",
    entry: "src/entries/drive.css",
    output: "css/generated/drive.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/drive.css instead. */",
  }),
  Object.freeze({
    id: "replay.styles",
    kind: "bundle",
    entry: "src/entries/replay.css",
    output: "css/generated/replay.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/replay.css instead. */",
  }),
  Object.freeze({
    id: "settings.styles",
    kind: "bundle",
    entry: "src/entries/settings.css",
    output: "css/generated/settings.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/settings.css instead. */",
  }),
  Object.freeze({
    id: "tools.styles",
    kind: "bundle",
    entry: "src/entries/tools.css",
    output: "css/generated/tools.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/tools.css instead. */",
  }),
  Object.freeze({
    id: "logs.styles",
    kind: "bundle",
    entry: "src/entries/logs.css",
    output: "css/generated/logs.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/logs.css instead. */",
  }),
  Object.freeze({
    id: "terminal.styles",
    kind: "bundle",
    entry: "src/entries/terminal.css",
    output: "css/generated/terminal.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal.css instead. */",
  }),
  Object.freeze({
    id: "terminal.guest-styles",
    kind: "bundle",
    entry: "src/entries/terminal_guest.css",
    output: "css/generated/terminal-guest.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/terminal_guest.css instead. */",
  }),
  Object.freeze({
    id: "intro.styles",
    kind: "bundle",
    entry: "src/entries/intro.css",
    output: "css/generated/intro.css",
    banner: "/* @generated by web/build.mjs; edit web/src/entries/intro.css instead. */",
  }),
]);

export const workerDefinitions = Object.freeze([
  Object.freeze({ id: "vision.webgl2.worker", path: "js/realtime/vision_webgl2_worker.js" }),
  Object.freeze({
    id: "navigation.media.worker",
    entry: "src/features/drive/contents/carrot_navi/worker.js",
    output: "js/realtime/drive_contents/carrot_navi/worker.js",
    banner: "/* @generated by web/build.mjs; edit web/src/features/drive/contents/carrot_navi/worker.js instead. */",
  }),
  Object.freeze({
    id: "drive.vision.ar.worker",
    entry: "src/features/drive/contents/vision/ar/worker.js",
    output: "js/realtime/drive_contents/vision/ar/worker.js",
    banner: "/* @generated by web/build.mjs; edit web/src/features/drive/contents/vision/ar/worker.js instead. */",
  }),
  Object.freeze({ id: "replay.sensor.worker", path: "js/realtime/replay_sensor_worker.js" }),
  Object.freeze({ id: "replay.advanced.worker", path: "js/realtime/replay_advanced_worker.js" }),
  Object.freeze({ id: "replay.log.worker", path: "js/realtime/replay_log_worker.js" }),
  Object.freeze({
    id: "logs.route-summary.worker",
    entry: "src/features/logs/route_summary/worker.js",
    output: "js/realtime/route_summary_worker.js",
    banner: "/* @generated by web/build.mjs; edit web/src/features/logs/route_summary/worker.js instead. */",
  }),
  Object.freeze({ id: "replay.video.worker", path: "js/realtime/replay_video_worker.js" }),
]);

export const assetManifestDefinition = Object.freeze({
  schemaVersion: 1,
  output: "generated/asset-manifest.json",
});

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function assetContentHash(bytes) {
  const normalized = Buffer.from(bytes.toString("utf8").replaceAll("\r\n", "\n"), "utf8");
  return sha256(normalized);
}

function workerOutput(definition) {
  return definition.output || definition.path;
}

async function normalizeGeneratedText(path) {
  const source = await readFile(path, "utf8");
  const normalized = source
    .replace(/[ \t]+$/gm, "")
    .replace(/^ +(?=\t)/gm, "");
  if (normalized !== source) await writeFile(path, normalized, "utf8");
}

export async function readValidatedDriveContentCatalog(root = webRoot) {
  const sourcePath = resolve(root, driveContentCatalogDefinition.source);
  let catalog;
  try {
    catalog = JSON.parse(await readFile(sourcePath, "utf8"));
  } catch (error) {
    throw new Error(`Drive content catalog cannot be read: ${sourcePath}`, { cause: error });
  }
  const normalized = validateDriveContentCatalog(catalog);
  const catalogIds = normalized.contents.map(({ id }) => id);
  const factoryIds = [...driveContentCatalogDefinition.factoryIds];
  if (catalogIds.length !== factoryIds.length
      || catalogIds.some((id, index) => id !== factoryIds[index])) {
    throw new Error(
      `Drive content catalog/factory ids must match exactly: catalog=[${catalogIds.join(",")}] factories=[${factoryIds.join(",")}]`,
    );
  }
  return normalized;
}

async function buildAssetManifest(outputRoot) {
  const assets = [];
  for (const definition of bundleDefinitions) {
    const bytes = await readFile(resolve(outputRoot, definition.output));
    assets.push({
      id: definition.id,
      kind: definition.kind,
      source: definition.entry,
      path: definition.output,
      hash: assetContentHash(bytes),
    });
  }
  for (const definition of workerDefinitions) {
    const path = workerOutput(definition);
    const sourceRoot = definition.entry ? outputRoot : webRoot;
    const bytes = await readFile(resolve(sourceRoot, path));
    assets.push({
      id: definition.id,
      kind: "worker",
      path,
      hash: assetContentHash(bytes),
    });
  }

  const ids = new Set(assets.map(({ id }) => id));
  const paths = new Set(assets.map(({ path }) => path));
  if (ids.size !== assets.length || paths.size !== assets.length) {
    throw new Error("Asset manifest ids and paths must be unique");
  }
  return { schemaVersion: assetManifestDefinition.schemaVersion, assets };
}

async function writeAssetManifest(outputRoot) {
  const manifest = await buildAssetManifest(outputRoot);
  const outputPath = resolve(outputRoot, assetManifestDefinition.output);
  const temporaryPath = `${outputPath}.${process.pid}-${randomUUID()}.tmp`;
  await mkdir(dirname(outputPath), { recursive: true });
  try {
    await writeFile(temporaryPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    await rename(temporaryPath, outputPath);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

export async function buildWeb({ outputRoot } = {}) {
  const requestedOutputRoot = outputRoot ?? process.env.CARROT_WEB_TEST_OUTDIR;
  const buildOutputRoot = requestedOutputRoot ? resolve(requestedOutputRoot) : webRoot;

  await readValidatedDriveContentCatalog();

  for (const definition of bundleDefinitions) {
    const bannerType = definition.output.endsWith(".css") ? "css" : "js";
    await build({
      entryPoints: [resolve(webRoot, definition.entry)],
      outfile: resolve(buildOutputRoot, definition.output),
      bundle: true,
      platform: "browser",
      format: "iife",
      target: ["chrome100"],
      charset: "utf8",
      legalComments: "none",
      minify: true,
      sourcemap: false,
      banner: { [bannerType]: definition.banner },
    });
    await normalizeGeneratedText(resolve(buildOutputRoot, definition.output));
  }
  for (const definition of workerDefinitions) {
    if (!definition.entry) continue;
    await build({
      entryPoints: [resolve(webRoot, definition.entry)],
      outfile: resolve(buildOutputRoot, workerOutput(definition)),
      bundle: true,
      platform: "browser",
      format: "iife",
      target: ["chrome100"],
      charset: "utf8",
      legalComments: "none",
      minify: true,
      sourcemap: false,
      banner: { js: definition.banner },
    });
    await normalizeGeneratedText(resolve(buildOutputRoot, workerOutput(definition)));
  }
  await writeAssetManifest(buildOutputRoot);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(buildFile)) await buildWeb();
